---
# --- XDG Base Dirs ----
xdg_config_home: "{{ ansible_env.HOME }}/.config"
xdg_data_home: "{{ ansible_env.HOME }}/.local/share"
xdg_cache_home: "{{ ansible_env.HOME }}/.cache"
xdg_state_home: "{{ ansible_env.HOME }}/.local/state"

set_zsh_as_login_shell: true  # Flag to control chsh command

user_config_home: "{{ ansible_env.HOME }}/myconfig"
nvim_github: "https://github.com/teaVeloper/teacup.nvim"
nvim_repo: "{{ user_config_home }}/nvim"
dotfiles_github: "https://github.com/teaVeloper/teaShellF"
dotfiles_repo: "{{ user_config_home }}/dotfiles"
