---
- name: Configure Desktop Machine
  hosts: localhost
  become: true
  vars:
    package_cats:
      - base
      - development
      - laptop
      - computational-science

  roles:
    - role: 01_basics
    - role: 02_packages
    - role: 03_desktop
    - role: 04_pass
    - role: 05_bluetooth
    - role: 06_peripherals
    - role: 07_dotfiles
    - role: 08_laptop
